### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by S-rz** [rootlu/DyHNE#1]
Hi, thanks for your codes . 
I read your paper and I want to know how can I get heterogeneous network dataset with time information？
Thanks again .

**Comment by rootlu** [comment]
Hi,
Actually, most heterogeneous networks only contain timestamp on a specific edge.
For example, we can construct a Yelp dataset containing user-item edge with timestamp.

In our work, two of the three data sets we use contain time information (i.e., Yelp and AMiner). Detailed datasets are being collated and will be released as soon as possible.

Thank you.
