### ISSUE TITLE
关于求解delta_U过程中的alpha矩阵中出现inf的问题

### ISSUE THREAD

**Issue by Dpens** [rootlu/DyHNE#3]
作者您好，我在使用python复现DyHNE时出现以下的问题。
我将数据集分成了10份，来模拟图的动态变化，但在计算delta_U的过程中，用来辅助计算矩阵A和delta_U的中间变量alpha矩阵的值会急速变大，并在几次动态变化后达到inf，导致最后得到的embedding全是nan。请问您是怎么解决这个问题的？
![image](https://user-images.githubusercontent.com/30972859/97768673-b0fac680-1b5f-11eb-81cc-dd8216a6ad22.png)

**Comment by rootlu** [comment]
你好，
请问Matlab代码有出现这个问题么？
你可以尝试把中间变量（例如A，B，C）打印出来观察分析一下，定位一下出现问题的具体位置？

**Comment by Dpens** [comment]
你好，DyHNE相关的matlab代码不是完整的，我们没有办法去验证代码是否有问题。
在我们复现的python代码中，我们分析是C在计算过程中增长速度较快的原因，导致alpha急速增大。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rootlu/DyHNE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 下午2:30
收件人:&nbsp;"rootlu/DyHNE"<DyHNE@noreply.github.com&gt;;
抄送:&nbsp;"啥也不想干的咸鱼"<514682604@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootlu/DyHNE] 关于求解delta_U过程中的alpha矩阵中出现inf的问题 (#3)





 
你好，
 请问Matlab代码有出现这个问题么？
 你可以尝试把中间变量（例如A，B，C）打印出来观察分析一下，定位一下出现问题的具体位置？

**Comment by rootlu** [comment]
你好，

matlab的代码是完整可运行的，你有尝试运行么？或是运行中有什么问题？matlab版本是否一致？

不太清楚你的Python代码的具体实现细节，所以不太容易定位具体问题。

**Comment by Dpens** [comment]
您好，
在您的所有动态模型的matlab代码中，都出现了DHINOnline这个函数，但是我没法从你的代码中找到它。我想看看这里的具体实现细节，以便找到我们复现的代码中的问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rootlu/DyHNE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 晚上10:21
收件人:&nbsp;"rootlu/DyHNE"<DyHNE@noreply.github.com&gt;;
抄送:&nbsp;"啥也不想干的咸鱼"<514682604@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootlu/DyHNE] 关于求解delta_U过程中的alpha矩阵中出现inf的问题 (#3)





 
你好，
 
matlab的代码是完整可运行的，你有尝试运行么？或是运行中有什么问题？matlab版本是否一致？
 
不太清楚你的Python代码的具体实现细节，所以不太容易定位具体问题。

**Comment by rootlu** [comment]
你好，

我更新了代码，现在可以查看。

**Comment by Dpens** [comment]
您好， 麻烦你了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Yuanfu&amp;nbsp;Lu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月1日(星期天) 晚上11:34
收件人:&nbsp;&quot;rootlu/DyHNE&quot;<DyHNE@noreply.github.com&gt;;
抄送:&nbsp;&quot;Dpens&quot;<514682604@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootlu/DyHNE] 关于求解delta_U过程中的alpha矩阵中出现inf的问题 (#3)

**Comment by rootlu** [comment]
感谢对我们工作的关注！
